Add package
Note the "uu" namespace clashes with the "uu" module name from the stdlib unfortunately. Working around it via the following:

- Keep distribution name uu.task.
- Use namespace "_uu" instead of "uu".

---

FYI the "uu" namespace produces this unhelpful error:

    alexclark@MH01936448MACLT:~/Developer/uu.task/ > bin/buildout
    --------------------------------------------------------------------------------
    Downloading zc.buildout bootstrap.py file from:
      https://bootstrap.pypa.io/bootstrap-buildout.py
    To:
      /Users/alexclark/Developer/uu.task/bootstrap.py
    --------------------------------------------------------------------------------
    mr.developer: Creating missing sources dir /Users/alexclark/Developer/uu.task/src.
    Develop: '/Users/alexclark/Developer/uu.task/.'
    Traceback (most recent call last):
      File "/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpvdtSY6", line 6, in <module>
        import os, setuptools
      File "/Users/alexclark/Developer/uu.task/lib/python2.7/site-packages/setuptools/__init__.py", line 11, in <module>
        from setuptools.extension import Extension
      File "/Users/alexclark/Developer/uu.task/lib/python2.7/site-packages/setuptools/extension.py", line 8, in <module>
        from .dist import _get_unpatched
      File "/Users/alexclark/Developer/uu.task/lib/python2.7/site-packages/setuptools/dist.py", line 19, in <module>
        import pkg_resources
      File "/Users/alexclark/Developer/uu.task/lib/python2.7/site-packages/pkg_resources/__init__.py", line 37, in <module>
        import email.parser
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/parser.py", line 12, in <module>
        from email.feedparser import FeedParser
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/feedparser.py", line 27, in <module>
        from email import message
      File "/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/email/message.py", line 10, in <module>
        import uu
      File "/Users/alexclark/Developer/uu.task/./uu/__init__.py", line 1, in <module>
        from pkg_resources import declare_namespace
    ImportError: cannot import name declare_namespace
    While:
      Installing.
      Processing develop directory '/Users/alexclark/Developer/uu.task/.'.

    An internal error occurred due to a bug in either zc.buildout or in a
    recipe being used:
    Traceback (most recent call last):
      File "/Users/alexclark/Developer/uu.task/lib/python2.7/site-packages/zc/buildout/buildout.py", line 1946, in main
        getattr(buildout, command)(args)
      File "/Users/alexclark/Developer/uu.task/lib/python2.7/site-packages/zc/buildout/buildout.py", line 488, in install
        installed_develop_eggs = self._develop()
      File "/Users/alexclark/Developer/uu.task/lib/python2.7/site-packages/zc/buildout/buildout.py", line 730, in _develop
        zc.buildout.easy_install.develop(setup, dest)
      File "/Users/alexclark/Developer/uu.task/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 938, in develop
        call_subprocess(args)
      File "/Users/alexclark/Developer/uu.task/lib/python2.7/site-packages/zc/buildout/easy_install.py", line 159, in call_subprocess
        % repr(args)[1:-1])
    Exception: Failed to run command:
    '/Users/alexclark/Developer/uu.task/bin/python2.7', '/var/folders/l3/0qtfq47x0cz49s_7zmfdnvj8cc2z9t/T/tmpvdtSY6', '-q', 'develop', '-mxN', '-d', '/Users/alexclark/Developer/uu.task/develop-eggs/tmpbdbHqbbuild'